### ISSUE TITLE
examples throw error: µWebSockets

### ISSUE THREAD

**Issue by selimanac** [gamestdio/colyseus-defold#5]
Looks like µWebSockets removed: https://www.npmjs.com/package/uws

```colyseus-defold/server/node_modules/uws/uws.js:38
            throw new Error('Compilation of µWebSockets has failed and there is no pre-compiled binary ' +
            ^

Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
    at native (/Users/selimanac/Development/Defold/colyseus/colyseus-defold/server/node_modules/uws/uws.js:38:19)
    at Object.<anonymous> (/Users/selimanac/Development/Defold/colyseus/colyseus-defold/server/node_modules/uws/uws.js:42:3)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/selimanac/Development/Defold/colyseus/colyseus-defold/server/node_modules/colyseus/lib/Server.js:4:13)```

**Comment by endel** [comment]
Hi @selimanac, that's correct, the guys from `uws` removed their package from NPM (https://github.com/uNetworking/uWebSockets-node/issues/2#issuecomment-413235618)

I'd suggest removing `uws` from your project for now. If you figure out how to include the `uws` package again, let me know!

Cheers!

**Comment by subversivo58** [comment]
A quick note:

The package has been deprecated from NPM by the author who published an "empty" package plus the project follows to accompany version 0.15 of uWebSockets.

NPM does not delete previously published packages what happens is that one should seek the penultimate version publised of fixed way, example:

**package.json**

```json
{
    "dependencies": {
        "uws": "10.148.1"
    }
}
```

There is no need to exclude it from your project, just stick to the developer repository and update the integration form of this module when it publishes a new version.

* new bindings repository for node: https://github.com/uNetworking/uWebSockets-node/
* uWebSockets 0.15: https://github.com/uNetworking/v0.15

**NOTE: "to this date there is nothing published yet"**
